######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 10 08:39:20 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
